all: tutorial metropolis
tutorial: (pdf "tutorial")
metropolis: (svg "metropolis-reverse") (svg "metropolis-customized") (pdf "metropolis-slides")

pdf name:
    typst c {{name}}.typ

svg name:
    typst c -f svg {{name}}.typ
